"""
publisher.py — serialize GameState and publish to Redis pub/sub + snapshot key.

D-03: Snapshot stored as Redis string key (SNAPSHOT_KEY) — late joiners read this on connect.
D-04: Full GameState on every broadcast (no deltas).
D-06: Called at each phase transition by the broadcast_fn callback in game.py.

Order matters: SET snapshot BEFORE PUBLISH — eliminates late-joiner race window (Pitfall 4).
Serialization: model_dump_json(by_alias=True) produces camelCase JSON matching types.ts GameState.
"""
from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING

import redis.asyncio as redis

from app.engine.models import GameState

if TYPE_CHECKING:
    from app.broadcast.broker import EventBroker

logger = logging.getLogger(__name__)

CHANNEL = "game:state"
SNAPSHOT_KEY = "game:state:last"
SNAPSHOT_TTL = 3600  # 1 hour — prevents stale snapshot persisting across long server restarts
REASONING_CHANNEL = "game:reasoning"
REASONING_SNAPSHOT_KEY = "game:reasoning:current"  # Redis list of reasoning delta JSON strings
GAME_LAST_RESULT_KEY = "game:last_result"


async def publish(redis_client: redis.Redis, state: GameState) -> None:
    """
    Serialize state as camelCase JSON, write to Redis snapshot key, then publish to channel.

    Args:
        redis_client: redis.asyncio.Redis with decode_responses=False
        state: Current GameState — serialized with by_alias=True for camelCase field names
    """
    payload = state.model_dump_json(by_alias=True)  # camelCase JSON matching types.ts
    # Clear reasoning snapshot only at hand start — late joiners can recover mid-hand reasoning.
    if state.phase == "pre-flop":
        await redis_client.delete(REASONING_SNAPSHOT_KEY)
    # SET before PUBLISH: late joiner arriving between these two ops sees the snapshot
    await redis_client.set(SNAPSHOT_KEY, payload, ex=SNAPSHOT_TTL)
    await redis_client.publish(CHANNEL, payload)
    logger.debug("Published game state (phase=%s, payload_len=%d)", state.phase, len(payload))


async def publish_reasoning(
    redis_client: redis.Redis,
    player_id: str,
    phase: str,
    delta: str,
    done: bool,
) -> None:
    """
    Publish a reasoning token delta to the reasoning Redis channel (D-01, D-02).

    Called by decision.py on each streaming chunk and once with done=True at stream end.
    Payload is camelCase to match TypeScript ReasoningEntry.delta expectation.

    Args:
        redis_client: Shared redis.asyncio.Redis connection
        player_id:    Player model ID (e.g. "gpt4", "gemini") — matches TypeScript ModelId
        phase:        Current game phase (e.g. "pre-flop", "flop")
        delta:        Token delta string; empty string ("") on final done=True call
        done:         True on the final event for this player's reasoning turn
    """
    payload = json.dumps({
        "playerId": player_id,
        "phase": phase,
        "delta": delta,
        "done": done,
    })
    await redis_client.publish(REASONING_CHANNEL, payload)
    # Append delta to reasoning snapshot — allows reconnecting clients to recover current reasoning.
    await redis_client.rpush(REASONING_SNAPSHOT_KEY, payload)
    await redis_client.expire(REASONING_SNAPSHOT_KEY, SNAPSHOT_TTL)
    logger.debug(
        "Published reasoning delta (player=%s, phase=%s, done=%s, delta_len=%d)",
        player_id, phase, done, len(delta),
    )


async def publish_game_status(
    broker: "EventBroker",
    redis_client: redis.Redis,
    running: bool,
) -> None:
    """
    Broadcast game_status event directly to all connected clients via broker.broadcast().
    Does NOT use Redis pub/sub — game_status is always generated by the local process.
    When running=False, reads game:last_result from Redis to include lastWinner.
    """
    if running:
        payload = json.dumps({"running": True})
    else:
        last_result_raw = await redis_client.get(GAME_LAST_RESULT_KEY)
        last_winner = None
        if last_result_raw:
            data = json.loads(
                last_result_raw.decode("utf-8") if isinstance(last_result_raw, bytes)
                else last_result_raw
            )
            last_winner = {
                "name": data["winnerName"],
                "org": data["winnerOrg"],
                "hand": data["winnerHand"],
            }
        payload = json.dumps({"running": False, "lastWinner": last_winner})

    envelope = json.dumps({"event": "game_status", "data": payload})
    await broker.broadcast(envelope)
